### ISSUE TITLE
MessageProcessor Error

### ISSUE THREAD

**Issue by huwrobertsjisc** [jiscdev/udd-web-validator#116]
Found the following error in the Event Log when validating against v1.2.7 TSV data:

Application: MessageProcessor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.Linq.Enumerable.Select[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,System.__Canon>)
   at UddModelExtractor.ComponentsExtractor.SetValidValuesIfExists(System.String, Int32, Int32, System.String)
   at UddModelExtractor.ComponentsExtractor.SetFieldTypeAndPrecisionForAllComponentFields(System.String, UddModelExtractor.Models.Component, Int32)
   at UddModelExtractor.ComponentsExtractor.ExtractAllComponents(System.Collections.Generic.List`1<System.String>)
   at MessageProcessor.Tools.UddComponentsExtractor.FetchComponentsFromGitHub(System.String)
   at MessageProcessor.Tools.UddComponentsExtractor.GetAllActiveComponentVersions()
   at MessageProcessor.ApiWorkerProcessor.FetchAndProcessOnLoop()
   at MessageProcessor.Program.Main()

**Comment by huwrobertsjisc** [comment]
Refactored code and added a try catch block to prevent the error from happening and closing the Message Processor down unexpectedly.

**Comment by huwrobertsjisc** [comment]
Promoted into UAT on the 30th of November 2017.
